### ISSUE TITLE
database sink

### ISSUE THREAD

**Issue by alexec** [argoproj-labs/argo-dataflow#146]
As a user I'd like to be able to sink messages to a database. Open questions:

* Sink to a single table presumably?
* How do we define the statement to execute?
* Inserts only? What about primary key conflicts?

See #147

**Comment by domderen** [comment]
I think such a sink could be a one or more queries that should be executed, that are templated by data contained within the message that was sent to the sink. For example something like this:

```
    sinks:
    - sql:
        host: my-db-host
        port: 5432
        database: my-db
        username-secret:
          name: my-secret-object-name
          key: key-with-username-property
        password-secret:
          name: my-secret-object-name
          key: key-with-password-property
        query: |
        INSERT INTO my-table (field1, field2) values ({{message.fieldInMessage}}, {{message.different.nested.field.in.message}});
        UPDATE my-table field3 = {{message.fieldInMessage}} WHERE field4 = {{message.different.nested.field.in.message}};
```

Maybe something like this? We might also need some additional data transformations to pass data from the incomming message in the right data format etc.

**Comment by alexec** [comment]
I think the syntax would be slightly different (to be consistent with the database/sql Golang package) and so we can use prepared statement for performance and security, and we can use expression syntax for args to allow users to do some transformation:

```yaml
sql:
  driverName: mysql
  dataSourceName: 
   valueFrom:
     secretKeyRef: 
       name: my-db
       key: my-key
    queries:
    - query: insert into my-table (field1, field2) values (?, ?)
      args:
      - object(msg).field1
      - object(msg).field2
      onConflict:
        query: updated my-table field1 = ? where field2 = ?
         args:
        - object(msg).field1
        - object(msg).field2
    - query: updated my-table field3 = ?
       args:
      - object(msg).field3
```

That would be transactional of course.
