### ISSUE TITLE
database source

### ISSUE THREAD

**Issue by alexec** [argoproj-labs/argo-dataflow#147]
As a user, I'd like to process records from a database.

* How do I define the query?
* Do I need to action new records? I.e. each new record is a new message.

See #146

**Comment by domderen** [comment]
I would also ask, if it would need to be cron based, and just repeat a query on a time interval? Would it be able to distinguish new results coming from the query, compared to previous execution? To only send messages when new rows are returned from the query etc... Are there database pub/sub interfaces, we could leverage here?

**Comment by alexec** [comment]
Something like:

- The user should be able to specify an SQL statement. 
- This statement could take one or more parameters (which could be used to resume).
- The statement could be run on a cron.


```yaml
statement: select * from my_table where uid >= ? order by uid
initialParameters:
- "0" 
parameters: 
- record.uid
```
