### ISSUE TITLE
Consume/Produce multiple kafka messages at once in git step / handlers

### ISSUE THREAD

**Issue by domderen** [argoproj-labs/argo-dataflow#158]
In certain situations, when message processing is slow, and relies heavily on network requests, it can be parallelized by grabbing multiple incoming messages from the source and processing them concurrently. This can provide better scalability than processing one message at a time, and leaving the process idle waiting for network responses.

Similarly, when messages are being inserted into the database, it might be better to perform batch inserts rather than inserting one message at a time.

For such usecases I would like to update kafka source definition like this:

```yaml
sources:
- kafka:
    topic: input-topic
    maxMessages: 5 // Maximum number of messages to pick at once from the kafka source
    timeout: 1 // Maximum number of seconds to wait if there aren't {{maxMessages}} in the topic yet. Can be 0, which means kafka should not wait at all, and just return what is in the topic immediately.
```

And the handler function in git step or in handler:

```go
package main

import "context"

func Handler(context context.Context, m [][]byte) ([][]byte, error) {
	responses := [][]byte{}
	for _, x := range m {
		responses = append(responses, []byte("hi "+string(x)))
	}
	return responses, nil
}
```

And similar changes for Java & Python environments.

I'm wondering if maybe there should be a way to tell handler/git step if it should expect one or more messages in the yaml, so that if user still expects just one message to come through, then they could use the previous handler function format?
