### ISSUE TITLE
Fetch private image

### ISSUE THREAD

**Issue by Udit107710** [argoproj-labs/argo-dataflow#183]
I was trying to fetch a private docker image with secrets in the namespace. 
```
      imagePullSecrets:
        - <secret-registery>
```
Unable to do so.

controller-gen.kubebuilder.io/version:  v0.4.1

**Comment by alexec** [comment]
I'm not sure I understand the problem. Could you share a bit more information please?

**Comment by domderen** [comment]
I think this is about extending the `container` step to allow this:

```python
from argo_dataflow import pipeline, container

if __name__ == '__main__':
    (pipeline("108-container")
     .owner('argoproj-labs')
     .describe("""This example showcases container options.""")
     .annotate('dataflow.argoproj.io/wait-for', 'Completed')
     .step(
        (container('main',
                   args=['sh', '-c', 'exit 0'],
                   image='private-registry.com/golang:1.16',
                   env={'FOO': 'bar'},
                   resources={'requests': {'cpu': 1}},
                   imagePullSecrets=({'name': 'docker-private-registry-com-secret'})
                   )
         .annotations({'my-annotation': 'my-value'})
         ))
     .save())

```


```yaml
apiVersion: dataflow.argoproj.io/v1alpha1
kind: Pipeline
metadata:
  annotations:
    dataflow.argoproj.io/description: This example showcases container options.
    dataflow.argoproj.io/owner: argoproj-labs
    dataflow.argoproj.io/wait-for: Completed
  name: 108-container
spec:
  steps:
  - container:
      args:
      - sh
      - -c
      - exit 0
      env:
      - name: FOO
        value: bar
      image: private-registry.com/golang:1.16
      resources:
        requests:
          cpu: 1
      imagePullSecrets:
      - name: docker-private-registry-com-secret
    metadata:
      annotations:
        my-annotation: my-value
    name: main
```

Where kubernetes would use this specific secret to pull the image defined in this container definition.

@alexec I can try to create a PR for this, if you think this approach makes sense?
