### ISSUE TITLE
Inconsistencies in step logs

### ISSUE THREAD

**Issue by inishchith** [argoproj-labs/argo-dataflow#232]
- Sometimes, all I see on the main step logs is this(image).
- Log starts pouring in only in case there's a large number of messages being pushed.

<img width="693" alt="Screenshot 2021-08-11 at 1 26 55 PM" src="https://user-images.githubusercontent.com/20226361/128992509-7dc9c130-58e8-4620-abb4-3bd72207f691.png">

Tested with Container step. Please let me know if something is unclear, happy to add more details/steps to reproduce.

Thanks!

**Comment by alexec** [comment]
Interesting. I don't really have enough detail to understand this. Can you share you example please?

**Comment by inishchith** [comment]
@alexec Sorry for the delayed response.


### Steps to reproduce

```yaml
apiVersion: dataflow.argoproj.io/v1alpha1
kind: Pipeline
metadata:
  annotations:
    dataflow.argoproj.io/description: |-
      Test Pipeline
    dataflow.argoproj.io/owner: df-team
    dataflow.argoproj.io/test: 'true'
  namespace: argo-dataflow-system
  name: test-pipeline
spec:
  steps:
  - container:
      image: <custom_image>
    sources:
    - kafka:
        name: default
        brokers:
          - '<broker-cluster-url>'
        topic: KAFKA_TOPIC
        startOffset: Last
    name: test-logging
```


- replace `<custom_image>` with image of [git-python](https://github.com/argoproj-labs/argo-dataflow/tree/main/examples/git-python).
- Once you run the pipeline successfully, it is supposed to log every message that pours into the `KAFKA_TOPIC`. But, you'll notice that the first few lines of log would be request info (like image shared above) and the logs would start pouring in only if there's a huge number of messages. I'm sure this isn't an expected behaviour.

LMK if something isn't clear, Thanks!
