### ISSUE TITLE
Ability add env to containers

### ISSUE THREAD

**Issue by radinv** [argoproj-labs/argo-dataflow#234]
Hi, we are using our kustomize, which needs to read environment variables in the argocd-repo-server container. Can you add the ability to define variables like we did in a non-operator setup?

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
  namespace: argocd
spec:
  replicas: 5
  template:
    spec:
      containers:
      - name: argocd-repo-server
        env:
          - name: CLUSTER
            value: prod
```

I think it should look something like this.

```
apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: example-argocd
  labels:
    example: repo
spec:
  repo:
    env: {}
```

Thanks!
