### ISSUE TITLE
Provide resource requests for controller and for argo-server

### ISSUE THREAD

**Issue by alexec** [argoproj-labs/argo-dataflow#247]
I don't like configuring these, it doesn't make sense for ever user to go through the act of configuration. Lets get some defaults in place.

**Comment by alexec** [comment]
Maybe:
```
spec:
  limits:
    - defaultRequest:
        memory: 126Mi
        cpu: 100m
      type: Container
```
