### ISSUE TITLE
Pipeline is deleted but Steps remain

### ISSUE THREAD

**Issue by Udit107710** [argoproj-labs/argo-dataflow#417]
Using `v0.0.115`

I deleted the Pipeline via UI

![image](https://user-images.githubusercontent.com/33377150/136062665-51990a33-5c93-42ca-841c-9afa576fa60e.png)

There are no pipelines in the namespace but steps are there and so are the pods associated with those steps

**Comment by alexec** [comment]
It looks like the steps got orphaned, but that should not happen. You're correct to expect them to be deleted.

When I do this myself, I deletes the steps too.

Could you should the full YAML for one of the orphaned steps?

**Comment by Udit107710** [comment]
```yaml
Name:         dataflow-pipeline-metatore-redis-sync-rt-filter-messages
Namespace:    argo
Labels:       dataflow.argoproj.io/pipeline-name=dataflow-pipeline-metatore-redis-sync-rt
              dataflow.argoproj.io/step-name=filter-messages
Annotations:  <none>
API Version:  dataflow.argoproj.io/v1alpha1
Kind:         Step
Metadata:
  Creation Timestamp:             2021-10-05T11:42:12Z
  Deletion Grace Period Seconds:  0
  Deletion Timestamp:             2021-10-05T14:55:49Z
  Finalizers:
    step-controller
  Generation:  2
  Managed Fields:
    API Version:  dataflow.argoproj.io/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .:
          v:"step-controller":
        f:labels:
          .:
          f:dataflow.argoproj.io/pipeline-name:
          f:dataflow.argoproj.io/step-name:
        f:ownerReferences:
          .:
          k:{"uid":"0e0d3df0-7984-4b8b-9e05-588b97bf79b0"}:
            .:
            f:apiVersion:
            f:blockOwnerDeletion:
            f:controller:
            f:kind:
            f:name:
            f:uid:
      f:spec:
        .:
        f:code:
          .:
          f:runtime:
          f:source:
        f:name:
        f:replicas:
        f:restartPolicy:
        f:scale:
          .:
          f:peekDelay:
          f:scalingDelay:
        f:serviceAccountName:
        f:sidecar:
          .:
          f:resources:
            .:
            f:limits:
              .:
              f:cpu:
              f:memory:
            f:requests:
              .:
              f:cpu:
              f:memory:
        f:sinks:
        f:sources:
      f:status:
        .:
        f:lastScaledAt:
        f:phase:
        f:replicas:
        f:selector:
    Manager:    manager
    Operation:  Update
    Time:       2021-10-05T11:42:15Z
  Owner References:
    API Version:           dataflow.argoproj.io/v1alpha1
    Block Owner Deletion:  true
    Controller:            true
    Kind:                  Pipeline
    Name:                  dataflow-pipeline-metatore-redis-sync-rt
    UID:                   0e0d3df0-7984-4b8b-9e05-588b97bf79b0
  Resource Version:        3864156
  UID:                     60867edf-c16e-40db-af74-a080f7ebdfca
Spec:
  Code:
---- REDACTED
  Name:            filter-messages
  Replicas:        1
  Restart Policy:  OnFailure
  Scale:
    Peek Delay:          defaultPeekDelay
    Scaling Delay:       defaultScalingDelay
  Service Account Name:  pipeline
  Sidecar:
    Resources:
      Limits:
        Cpu:     500m
        Memory:  256Mi
      Requests:
        Cpu:     100m
        Memory:  64Mi
  Sinks:
    Kafka:
      Brokers:
        kafka-headless.kafka.svc.cluster.local:9092
      Name:   default
      Topic:  redis_sink_intermediate_store
    Name:     default
  Sources:
    Kafka:
      Auto Commit:
        Enable:  false
      Brokers:
        kafka-headless.kafka.svc.cluster.local:9092
      Name:          default
      Start Offset:  Last
      Topic:         ATLAS_ENTITIES
    Name:            default
    Retry:
      Cap:                0s
      Duration:           100ms
      Factor Percentage:  200
      Jitter Percentage:  10
      Steps:              20
Status:
  Last Scaled At:  2021-10-05T11:42:12Z
  Phase:           Running
  Replicas:        1
  Selector:        dataflow.argoproj.io/pipeline-name=dataflow-pipeline-metatore-redis-sync-rt,dataflow.argoproj.io/step-name=filter-messages
Events:            <none>
```
