### ISSUE TITLE
Configuration Python DSL

### ISSUE THREAD

**Issue by alexec** [argoproj-labs/argo-dataflow#445]
Users would like to create shared configuration in the Python DSL, and then have that mounted on their containers. 

The DSL is a transpiler. Maybe something like this?

```python
config = {'foo': 1, 'bar': 'baz'}

// ...
pipeline()...
  step(container(config=config))
  save()
````

Could result in:

```yaml
kind: ConfigMap:
metadata
  name: dataflows-config-0000
stringData:
  foo: "1"
  bar: baz
````

```yaml
kind: Pipeline
spec:
  steps:
  - name: main
     container:
       volumes:
       - name: config
          path: /var/run/argo/config
          valueFrom:
             configMap: 
             - name: dataflow-config-0000
````
