### ISSUE TITLE
Step retrying even after updating to not retry 

### ISSUE THREAD

**Issue by Udit107710** [argoproj-labs/argo-dataflow#461]
Using 0.1.0

I deployed a new pipeline with default retry strategy and encountered some errors inside my container which started resulting in Dataflow retrying for those particular messages. 
I updated my spec to below added snippet and expected that the retry would stop but the retries didn't stop for that message
Is this expected behaviour?

Step spec:
```yaml
spec:
  steps:
  - container:
      image: abc
    name: enrich-query
    scale:
      desiredReplicas: limit(currentReplicas + pendingDelta / (60 * 250) + pending
        / (10 * 60 * 250), 1, 3, 1)
      peekDelay: |-
        "20m"
      scalingDelay: |-
        "1m"
    sources:
    - kafka:
        name: TOPIC
        topic: TOPIC
        brokers:
          - 'kafka-headless.kafka.svc.cluster.local:9092'
        startOffset: Last
      retry:
        steps: 0
```
Referenced: https://raw.githubusercontent.com/argoproj-labs/argo-dataflow/main/examples/301-erroring-pipeline.yaml
