### ISSUE TITLE
Kubernetes event source

### ISSUE THREAD

**Issue by alexec** [argoproj-labs/argo-dataflow#50]
It might be useful to directly consume Kubernetes events as a source, saving any need to write any code.

```yaml
sources:
- name: events 
  kubernetesEvents:
    namespace: All
```
