### ISSUE TITLE
Bucket contents source/sink

### ISSUE THREAD

**Issue by alexec** [argoproj-labs/argo-dataflow#51]
It might be useful to be able to source or sink data from/to buckets (e.g. S3)

```yaml
sources:
- s3: 
    bucket: my-bucket
    filename: *.log
```

Each item in the bucket is a single data item. Any new items appear, these are automatically found and sent.

Sinks are a bit simpler, but we need to determine the filename:

```yaml
sinks:
- s3: 
    bucket: my-bucket
    filename: meta.filename // an expression from the message context? just a random GUID?
```
